/*
*	New C++ Header  File starts here.
*	This file should be named nmlNav_n_codegen_protos.hh
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=nmlNav.h HHFile=-o HHFile=nmlNav.cpp
*	RCS_VERSION=@(#) RCS_LIBRARY_VERSION: 2009.02.10_1384:1390 Compiled on Thu Feb 12 11:13:40 EST 2009 for the java platform.
*	$Id: CodeGenCommon.java 1341 2009-02-05 21:22:54Z shackle $
*
*	.gen script :
*		0:load nmlNav.h
*		1:clear
*		2:select_from_file nmlNav.h
*		3:generate C++ protos>nmlNav_n_codegen_protos.hh
*
*/

#ifndef nmlNav_n_codegen_protos_hh_included
#define nmlNav_n_codegen_protos_hh_included

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "nmlNav.h"

// Forward Function Prototypes


#ifndef MAX_EX_NAME_LENGTH
#define MAX_EX_NAME_LENGTH 12
#endif
#ifndef EX_NAME_LIST_LENGTH
#define EX_NAME_LIST_LENGTH 2
#endif


/* This list must be in alphabetical order and the three lists must correspond. */
extern const NMLTYPE ex_id_list[EX_NAME_LIST_LENGTH];
extern const size_t ex_size_list[EX_NAME_LIST_LENGTH];

// Enumerated Type Constants

extern int ex_format(NMLTYPE type, void *buffer, CMS *cms);

#endif
	/* # endif nmlNav_n_codegen_protos_hh_included */ 

