/*
*	New C++ File starts here.
*	This file should be named nmlNav.cc
*	Automatically generated by NML CodeGen Java Applet.
*	with command line arguments :  HHFile=nmlNav.h HHFile=-o HHFile=nmlNav.cpp
*	RCS_VERSION=@(#) RCS_LIBRARY_VERSION: 2009.02.10_1384:1390 Compiled on Thu Feb 12 11:13:40 EST 2009 for the java platform.
*	$Id: CodeGenCommon.java 1341 2009-02-05 21:22:54Z shackle $
*
*	.gen script :
*		0:load nmlNav.h
*		1:clear
*		2:select_from_file nmlNav.h
*		3:generate C++ protos>nmlNav_n_codegen_protos.hh
*		4:generate C++ format>nmlNav_n.cc
*
*/

// Include all NML, CMS, and RCS classes and functions
#include "rcs.hh"

// Include command and status message definitions
#include "nmlNav.h"

// Include externally supplied prototypes
#include "nmlNav_n_codegen_protos.hh"



#ifndef EX_NAME_LIST_LENGTH
#define EX_NAME_LIST_LENGTH 2
#endif

const NMLTYPE ex_id_list[EX_NAME_LIST_LENGTH]= {
	NAVDATA_MSG_TYPE, /* 0,101 */
	-1};
const size_t ex_size_list[EX_NAME_LIST_LENGTH]= {
	sizeof(NAVDATA_MSG),
	0};


// Enumerated Type Constants

/*
Estimated_size	NAVDATA_MSG	64
Estimated_size	MAXIMUM	64
*/
/*
*	NML/CMS Format function : ex_format
*/
int ex_format(NMLTYPE type, void *buffer, CMS *cms)
{

	type = cms->check_type_info(type,buffer,"ex",
		(cms_symbol_lookup_function_t) 0,
		(const char **) 0,
		ex_id_list,ex_size_list,
		EX_NAME_LIST_LENGTH,
		0);

	switch(type)
	{
	case NAVDATA_MSG_TYPE:
		((NAVDATA_MSG *) buffer)->update(cms);
		break;

	default:
		return(0);
	}
	return 1;
}

/*
*	NML/CMS Update function for NAVDATA_MSG
*	from nmlNav.h:0
*/
void NAVDATA_MSG::update(CMS *cms)
{

	cms->beginClass("NAVDATA_MSG","NMLmsg");
	cms->update_with_name("xAccel",xAccel);
	cms->update_with_name("yAccel",yAccel);
	cms->update_with_name("zAccel",zAccel);
	cms->update_with_name("xVelocity",xVelocity);
	cms->update_with_name("yVelocity",yVelocity);
	cms->update_with_name("zVelocity",zVelocity);
	cms->update_with_name("xDistance",xDistance);
	cms->update_with_name("yDistance",yDistance);
	cms->update_with_name("zDistance",zDistance);
	cms->update_with_name("heading",heading);
	cms->update_with_name("pitch",pitch);
	cms->update_with_name("roll",roll);

	cms->endClass("NAVDATA_MSG","NMLmsg");

}

/*
*	Constructor for NAVDATA_MSG
*	from nmlNav.h:0
*/
NAVDATA_MSG::NAVDATA_MSG()
	: NMLmsg(NAVDATA_MSG_TYPE,sizeof(NAVDATA_MSG))
{
	xAccel = (float) 0;
	yAccel = (float) 0;
	zAccel = (float) 0;
	xVelocity = (float) 0;
	yVelocity = (float) 0;
	zVelocity = (float) 0;
	xDistance = (float) 0;
	yDistance = (float) 0;
	zDistance = (float) 0;
	heading = (float) 0;
	pitch = (float) 0;
	roll = (float) 0;

}

